const state={fixtures:[
{id:1,date:'2026-09-12',home:"St Paul's",away:'Malahide',venue:'TBC',status:'upcoming',scouted:false},
{id:2,date:'2026-09-19',home:'UCC',away:"St Paul's",venue:'Mardyke Arena',status:'upcoming',scouted:false},
{id:3,date:'2026-08-29',home:"St Paul's",away:'Fr Mathews',venue:'TBC',status:'final',scouted:true,score:'78–71',q:'19–16 · 21–18 · 17–20 · 21–17'},
{id:4,date:'2026-08-22',home:'Limerick Celtics',away:"St Paul's",venue:'Limerick',status:'final',scouted:true,score:'69–74',q:'17–19 · 16–18 · 20–17 · 16–20'},
{id:5,date:'2026-10-03',home:"St Paul's",away:'Belfast Star',venue:'TBC',status:'upcoming',scouted:false}
]};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function initials(t){return t.split(' ').map(x=>x[0]).join('').slice(0,3).toUpperCase()}
function fmt(d){return new Date(d+'T12:00:00').toLocaleDateString('en-IE',{day:'2-digit',month:'short',year:'numeric'})}
function fixtureRow(f){return `<div class="fixture"><div class="teams"><div class="team-badge">${initials(f.home)}</div><div><div class="date">${fmt(f.date)} · ${esc(f.venue)}</div><div class="opponent">${esc(f.home)} <span style="color:#98a2b3">vs</span> ${esc(f.away)}</div></div></div><div>${f.score?`<div class="result">${f.score}</div>`:''}</div><span class="badge ${f.scouted?'done':f.status==='upcoming'?'scout':''}">${f.scouted?'Scouted':f.status==='upcoming'?'To scout':'Final'}</span></div>`}
function dashboard(){const upcoming=state.fixtures.filter(f=>f.status==='upcoming').sort((a,b)=>a.date.localeCompare(b.date)); const done=state.fixtures.filter(f=>f.scouted); return `<div class="grid stats"><div class="card"><div class="metric-label">Next game</div><div class="metric">${upcoming[0]?fmt(upcoming[0].date):'—'}</div><div class="delta">${upcoming[0]?esc(upcoming[0].away):'No fixture'}</div></div><div class="card"><div class="metric-label">Fixtures</div><div class="metric">${state.fixtures.length}</div><div class="delta">${upcoming.length} upcoming</div></div><div class="card"><div class="metric-label">Games scouted</div><div class="metric">${done.length}</div><div class="delta positive">${Math.round(done.length/state.fixtures.length*100)}% coverage</div></div><div class="card"><div class="metric-label">Season record</div><div class="metric">2–0</div><div class="delta positive">+6.0 avg margin</div></div></div><div class="grid two"><div><div class="section-head"><h2>Upcoming fixtures</h2><button class="link" data-view-link="fixtures">View all →</button></div><div class="card">${upcoming.slice(0,3).map(fixtureRow).join('')}</div></div><div><div class="section-head"><h2>Opponent snapshot</h2></div><div class="card"><div class="metric-label">Malahide · next opponent</div><div class="metric">4–2</div><div class="delta">Historical record from available games</div><div class="bar-row"><span>3PT shooting</span><div class="bar"><i style="width:82%"></i></div><b>36.8%</b></div><div class="bar-row"><span>FG shooting</span><div class="bar"><i style="width:77%"></i></div><b>46.2%</b></div><div class="insight"><b>Scout focus</b><span>Build the opponent profile from verified game data before the next matchup.</span></div></div></div></div><div class="section-head"><h2>Recent results</h2><button class="link" data-view-link="reports">Reports →</button></div><div class="card">${done.map(fixtureRow).join('')}</div>`}
function fixtures(){return `<div class="card"><div class="section-head" style="margin-top:0"><div><h2>Season fixtures</h2><div class="metric-label">Every scheduled game lives here, whether scouted or not.</div></div><button class="primary" id="new-fixture-2">+ Add fixture</button></div><div>${state.fixtures.sort((a,b)=>a.date.localeCompare(b.date)).map(fixtureRow).join('')}</div></div>`}
function scouting(){return `<div class="grid three"><div class="card"><div class="metric-label">Games with verified data</div><div class="metric">${state.fixtures.filter(f=>f.scouted).length}</div><div class="delta">Source screenshots → verified stats</div></div><div class="card"><div class="metric-label">Teams in database</div><div class="metric">5</div><div class="delta">Growing automatically</div></div><div class="card"><div class="metric-label">Reports available</div><div class="metric">0</div><div class="delta">Generate after verification</div></div></div><div class="section-head"><h2>Scouting workflow</h2></div><div class="card"><div class="insight"><b>1 · Select fixture</b><span>Open an individual fixture without mixing it with another game.</span></div><div class="insight"><b>2 · Upload Swish screenshots</b><span>Attach source screenshots directly to that fixture.</span></div><div class="insight"><b>3 · OCR + verification</b><span>Extract player and team statistics, then review every value before it becomes canonical data.</span></div><div class="insight"><b>4 · Analyse</b><span>Build team/player trends from verified historical games.</span></div><div class="insight"><b>5 · Generate report</b><span>Produce a professional game or opponent scouting PDF.</span></div></div>`}
function teams(){return `<div class="card"><div class="section-head" style="margin-top:0"><h2>Teams</h2><span class="badge">Historical intelligence</span></div><table class="table"><thead><tr><th>Team</th><th>Games</th><th>Record</th><th>Scouting coverage</th></tr></thead><tbody>${['Malahide',"St Paul's",'UCC','Fr Mathews','Limerick Celtics'].map((t,i)=>`<tr><td><b>${t}</b></td><td>${i?2:6}</td><td>${i? '2–0':'4–2'}</td><td>${i?'33%':'83%'}</td></tr>`).join('')}</tbody></table></div>`}
function players(){return `<div class="card"><div class="section-head" style="margin-top:0"><h2>Players</h2><span class="badge">Powered by verified game data</span></div><div class="empty"><strong>No player database imported yet</strong>Upload and verify a Swish game to start building player histories.</div></div>`}
function reports(){return `<div class="grid two"><div class="card"><div class="metric-label">REPORT TYPE</div><div class="metric" style="font-size:20px">Opponent scouting</div><p style="color:#667085;font-size:13px;line-height:1.6">A coach-ready report combining recent form, team tendencies, player threats, strengths, weaknesses and game-plan priorities.</p><button class="primary">Generate when data is ready</button></div><div class="card"><div class="metric-label">REPORT TYPE</div><div class="metric" style="font-size:20px">Game report</div><p style="color:#667085;font-size:13px;line-height:1.6">A permanent record of one fixture: score, quarters, player statistics, team statistics and AI analysis.</p><button class="secondary">View report history</button></div></div>`}
function render(view='dashboard'){const titles={dashboard:'Overview',fixtures:'Fixtures',scouting:'Scouting',teams:'Teams',players:'Players',reports:'Reports'}; $('#page-title').textContent=titles[view]; $('#view').innerHTML={dashboard,fixtures,scouting,teams,players,reports}[view](); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>render(b.dataset.viewLink)); const n=$('#new-fixture-2'); if(n)n.onclick=openModal}
function openModal(){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box"><h2>Add fixture</h2><div class="form-grid"><div class="field"><label>DATE</label><input id="f-date" type="date"></div><div class="field"><label>VENUE</label><input id="f-venue" placeholder="Venue"></div><div class="field"><label>HOME TEAM</label><input id="f-home" value="St Paul's"></div><div class="field"><label>AWAY TEAM</label><input id="f-away" placeholder="Opponent"></div></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="save">Save fixture</button></div></div>`;document.body.appendChild(m);$('#cancel').onclick=()=>m.remove();$('#save').onclick=()=>{const date=$('#f-date').value,home=$('#f-home').value,away=$('#f-away').value;if(!date||!home||!away)return;state.fixtures.push({id:Date.now(),date,home,away,venue:$('#f-venue').value||'TBC',status:'upcoming',scouted:false});m.remove();render('fixtures')}}
$('#new-fixture').onclick=openModal; document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>render(b.dataset.view)); render();
