const STORAGE_KEY='courtiq-fixtures-v2';
const SCREENSHOT_KEY='courtiq-screenshots-v1';
const seedFixtures=[
{id:1,date:'2026-09-12',home:"St Paul's",away:'Malahide',venue:'TBC',status:'upcoming',scouted:false},
{id:2,date:'2026-09-19',home:'UCC',away:"St Paul's",venue:'Mardyke Arena',status:'upcoming',scouted:false},
{id:3,date:'2026-08-29',home:"St Paul's",away:'Fr Mathews',venue:'TBC',status:'final',scouted:true,score:'78–71',q:['19–16','21–18','17–20','21–17'],stats:{home:{fg:'28/61',three:'9/24',ft:'13/17',reb:38,ast:17,to:11},away:{fg:'25/63',three:'8/26',ft:'13/19',reb:34,ast:14,to:15}}},
{id:4,date:'2026-08-22',home:'Limerick Celtics',away:"St Paul's",venue:'Limerick',status:'final',scouted:true,score:'69–74',q:['17–19','16–18','20–17','16–20'],stats:{home:{fg:'26/62',three:'7/25',ft:'10/15',reb:35,ast:13,to:16},away:{fg:'27/59',three:'8/23',ft:'12/16',reb:39,ast:18,to:12}}},
{id:5,date:'2026-10-03',home:"St Paul's",away:'Belfast Star',venue:'TBC',status:'upcoming',scouted:false}
];
const state={fixtures:loadFixtures(),screenshots:loadScreenshots(),selectedFixture:null};
function loadFixtures(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(s)&&s.length?s:structuredClone(seedFixtures)}catch{return structuredClone(seedFixtures)}}
function loadScreenshots(){try{return JSON.parse(localStorage.getItem(SCREENSHOT_KEY))||{}}catch{return {}}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.fixtures));localStorage.setItem(SCREENSHOT_KEY,JSON.stringify(state.screenshots))}
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function initials(t){return t.split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase()}
function fmt(d){return new Date(d+'T12:00:00').toLocaleDateString('en-IE',{day:'2-digit',month:'short',year:'numeric'})}
function fixtureById(id){return state.fixtures.find(f=>f.id===Number(id))}
function shots(id){return state.screenshots[String(id)]||[]}
function statusBadge(f){return `<span class="badge ${f.scouted?'done':f.status==='upcoming'?'scout':''}">${f.scouted?'Scouted':f.status==='upcoming'?'To scout':'Final'}</span>`}
function fixtureRow(f){return `<button class="fixture fixture-button" data-fixture="${f.id}"><div class="teams"><div class="team-badge">${initials(f.home)}</div><div><div class="date">${fmt(f.date)} · ${esc(f.venue||'TBC')}</div><div class="opponent">${esc(f.home)} <span class="versus">vs</span> ${esc(f.away)}</div></div></div><div class="fixture-middle">${f.score?`<div class="result">${esc(f.score)}</div>`:'<span class="muted">Upcoming</span>'}</div>${statusBadge(f)}<span class="chevron">›</span></button>`}
function dashboard(){const upcoming=state.fixtures.filter(f=>f.status==='upcoming').sort((a,b)=>a.date.localeCompare(b.date));const done=state.fixtures.filter(f=>f.scouted);const next=upcoming[0];return `<div class="grid stats"><div class="card"><div class="metric-label">Next game</div><div class="metric small-metric">${next?fmt(next.date):'—'}</div><div class="delta">${next?esc(next.home)+' vs '+esc(next.away):'No fixture'}</div></div><div class="card"><div class="metric-label">Season fixtures</div><div class="metric">${state.fixtures.length}</div><div class="delta">${upcoming.length} upcoming</div></div><div class="card"><div class="metric-label">Games scouted</div><div class="metric">${done.length}</div><div class="delta positive">${state.fixtures.length?Math.round(done.length/state.fixtures.length*100):0}% coverage</div></div><div class="card"><div class="metric-label">Screenshots stored</div><div class="metric">${Object.values(state.screenshots).reduce((n,a)=>n+a.length,0)}</div><div class="delta">Fixture-scoped source evidence</div></div></div><div class="grid two"><div><div class="section-head"><div><h2>Upcoming fixtures</h2><span class="section-sub">Every fixture, whether scouted or not</span></div><button class="link" data-view-link="fixtures">View all →</button></div><div class="card list-card">${upcoming.slice(0,4).map(fixtureRow).join('')||'<div class="empty">No upcoming fixtures.</div>'}</div></div><div><div class="section-head"><div><h2>Next opponent</h2><span class="section-sub">${next?fmt(next.date):'—'}</span></div></div><div class="card"><div class="opponent-hero"><div class="team-badge large">${next?initials(next.away):'—'}</div><div><div class="metric-label">Opponent</div><div class="metric small-metric">${next?esc(next.away):'None'}</div><div class="delta">Verified data only</div></div></div><div class="insight"><b>Scout status</b><span>${next&&next.scouted?'Verified data available.':'No verified game data yet. Upload Swish screenshots when available.'}</span></div></div></div></div><div class="section-head"><div><h2>Recent results</h2><span class="section-sub">Completed games with verified data</span></div><button class="link" data-view-link="reports">Reports →</button></div><div class="card list-card">${done.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(fixtureRow).join('')}</div>`}
function fixtures(){const sorted=[...state.fixtures].sort((a,b)=>a.date.localeCompare(b.date));return `<div class="card"><div class="section-head flush"><div><h2>Season fixtures</h2><div class="metric-label">Your complete schedule. Scouting data attaches to a fixture but never defines whether the fixture exists.</div></div><button class="primary" id="new-fixture-2">+ Add fixture</button></div><div class="fixture-toolbar"><span>${sorted.length} fixtures</span><span>${sorted.filter(f=>f.status==='upcoming').length} upcoming · ${sorted.filter(f=>f.scouted).length} scouted</span></div>${sorted.map(fixtureRow).join('')}</div>`}
function gameDetail(id){const f=fixtureById(id);if(!f)return dashboard();const hasStats=!!f.stats;const files=shots(f.id);return `<div class="back-row"><button class="link" id="back-fixtures">← Back to fixtures</button>${statusBadge(f)}</div><div class="game-hero card"><div><div class="eyebrow">${fmt(f.date)} · ${esc(f.venue||'TBC')}</div><h2>${esc(f.home)} <span>vs</span> ${esc(f.away)}</h2><div class="game-status">${f.score?`Final · ${esc(f.score)}`:'Upcoming fixture · No verified game data'}</div></div><div class="game-actions"><button class="secondary" id="edit-fixture">Edit fixture</button><button class="primary" id="upload-scout">${files.length?'Add screenshots':'Start scouting'}</button></div></div><div class="grid two"><div class="card"><div class="section-head flush"><h2>Game data</h2><span class="badge">${hasStats?'Verified':'Not verified'}</span></div>${hasStats?statsTable(f):`<div class="empty"><strong>No verified statistics yet</strong><span>Upload Swish screenshots for this fixture. OCR candidates will be reviewed before anything becomes canonical data.</span><button class="primary empty-action" id="upload-empty">Upload screenshots</button></div>`}</div><div class="card"><div class="section-head flush"><h2>Quarter scores</h2></div>${f.q?`<div class="quarters">${f.q.map((q,i)=>`<div><span>Q${i+1}</span><b>${esc(q)}</b></div>`).join('')}</div>`:'<div class="empty compact">Quarter scores will appear after verification.</div>'}<div class="insight"><b>Fixture independence</b><span>This record only contains data attached to ${esc(f.home)} vs ${esc(f.away)} on ${fmt(f.date)}.</span></div></div></div><div class="section-head"><div><h2>Scouting workspace</h2><span class="section-sub">Source screenshots → OCR → verification → analysis</span></div><button class="secondary" id="manage-shots">${files.length} screenshot${files.length===1?'':'s'}</button></div>${files.length?`<div class="card screenshot-grid">${files.map((s,i)=>`<div class="shot-card"><img src="${s.data}" alt="${esc(s.name)}"><div><b>${esc(s.name)}</b><span>Source evidence · ${esc(s.status)}</span></div><button class="link danger" data-delete-shot="${i}">Remove</button></div>`).join('')}</div>`:'<div class="grid three"><div class="workflow card"><span>01</span><b>Source screenshots</b><p>Store Swish screenshots against this fixture.</p></div><div class="workflow card"><span>02</span><b>OCR + verification</b><p>Extract statistics and review every value.</p></div><div class="workflow card"><span>03</span><b>Scouting report</b><p>Generate opponent intelligence from verified games.</p></div></div>`}`}
function statsTable(f){const h=f.stats.home,a=f.stats.away;return `<table class="table"><thead><tr><th>Statistic</th><th>${esc(f.home)}</th><th>${esc(f.away)}</th></tr></thead><tbody>${[['FG',h.fg,a.fg],['3PT',h.three,a.three],['FT',h.ft,a.ft],['Rebounds',h.reb,a.reb],['Assists',h.ast,a.ast],['Turnovers',h.to,a.to]].map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td><b>${r[2]}</b></td></tr>`).join('')}</tbody></table>`}
function scouting(){const scouted=state.fixtures.filter(f=>f.scouted);const uploaded=Object.values(state.screenshots).reduce((n,a)=>n+a.length,0);return `<div class="grid three"><div class="card"><div class="metric-label">Verified games</div><div class="metric">${scouted.length}</div><div class="delta">Only verified data feeds analytics</div></div><div class="card"><div class="metric-label">Source screenshots</div><div class="metric">${uploaded}</div><div class="delta">Stored against fixtures</div></div><div class="card"><div class="metric-label">Teams encountered</div><div class="metric">${new Set(state.fixtures.flatMap(f=>[f.home,f.away])).size}</div><div class="delta">Built from fixture history</div></div></div><div class="section-head"><div><h2>Scouting workflow</h2><span class="section-sub">Start from a fixture, never from a loose screenshot</span></div></div><div class="card workflow-list">${[['1','Select fixture','Open an individual fixture without mixing it with another game.'],['2','Upload Swish screenshots','Attach source screenshots directly to that fixture.'],['3','OCR + verification','Extract statistics, flag uncertain values and review every field.'],['4','Analyse','Build team and player trends from verified historical games.'],['5','Generate report','Produce a professional game or opponent scouting PDF.']].map(x=>`<div class="insight"><b>${x[0]} · ${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div>`}
function teams(){const teams=[...new Set(state.fixtures.flatMap(f=>[f.home,f.away]))];return `<div class="card"><div class="section-head flush"><div><h2>Teams</h2><div class="metric-label">Historical intelligence is aggregated from independent fixture records.</div></div><span class="badge">${teams.length} teams</span></div><table class="table"><thead><tr><th>Team</th><th>Fixtures</th><th>Scouted games</th><th>Coverage</th></tr></thead><tbody>${teams.map(t=>{const fs=state.fixtures.filter(f=>f.home===t||f.away===t);const s=fs.filter(f=>f.scouted).length;return `<tr><td><b>${esc(t)}</b></td><td>${fs.length}</td><td>${s}</td><td>${Math.round(s/fs.length*100)}%</td></tr>`}).join('')}</tbody></table></div>`}
function players(){return `<div class="card"><div class="section-head flush"><div><h2>Players</h2><div class="metric-label">Player histories populate from verified Swish box-score data.</div></div></div><div class="empty"><strong>No player database imported yet</strong><span>Upload and verify a Swish game to start building player histories across fixtures.</span></div></div>`}
function reports(){return `<div class="grid two"><div class="card report-card"><div class="report-icon">OS</div><div class="metric-label">REPORT TYPE</div><div class="metric report-title">Opponent scouting</div><p>Coach-ready report combining recent form, team tendencies, player threats, strengths, weaknesses and game-plan priorities.</p><button class="primary">Generate when data is ready</button></div><div class="card report-card"><div class="report-icon">GR</div><div class="metric-label">REPORT TYPE</div><div class="metric report-title">Game report</div><p>Permanent record of one fixture: score, quarters, player statistics, team statistics and analysis.</p><button class="secondary">View report history</button></div></div><div class="section-head"><div><h2>Available game reports</h2><span class="section-sub">Generated from verified fixture data</span></div></div><div class="card list-card">${state.fixtures.filter(f=>f.scouted).map(f=>`<button class="report-row" data-fixture="${f.id}"><div><b>${esc(f.home)} vs ${esc(f.away)}</b><span>${fmt(f.date)} · ${esc(f.score||'')}</span></div><span>Game report →</span></button>`).join('')||'<div class="empty">No reports yet.</div>'}</div>`}
function render(view='dashboard'){const titles={dashboard:'Overview',fixtures:'Fixtures',scouting:'Scouting',teams:'Teams',players:'Players',reports:'Reports'};$('#page-title').textContent=titles[view];$('#view').innerHTML={dashboard,fixtures,scouting,teams,players,reports}[view]();wire();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function wire(){document.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=()=>render(b.dataset.viewLink));document.querySelectorAll('[data-fixture]').forEach(b=>b.onclick=()=>openGame(Number(b.dataset.fixture)));document.querySelectorAll('[data-delete-shot]').forEach(b=>b.onclick=()=>removeScreenshot(Number(b.dataset.deleteShot)));const n=$('#new-fixture-2');if(n)n.onclick=()=>openModal();const back=$('#back-fixtures');if(back)back.onclick=()=>render('fixtures');const edit=$('#edit-fixture');if(edit)edit.onclick=()=>openModal(state.selectedFixture);['upload-scout','upload-empty','manage-shots'].forEach(id=>{const b=$('#'+id);if(b)b.onclick=()=>openUpload(state.selectedFixture)})}
function openGame(id){state.selectedFixture=id;$('#page-title').textContent='Game';$('#view').innerHTML=gameDetail(id);wire()}
function openUpload(fixtureId){const f=fixtureById(fixtureId);if(!f)return;const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box upload-modal"><div class="eyebrow">${esc(f.home)} vs ${esc(f.away)}</div><h2>Upload Swish screenshots</h2><p class="modal-copy">Every image will be stored against this fixture only. Originals remain source evidence and are not treated as verified statistics.</p><label class="dropzone" id="dropzone"><input id="shot-files" type="file" accept="image/png,image/jpeg,image/webp" multiple><strong>Choose screenshots</strong><span>PNG, JPG or WebP · multiple files supported</span></label><div id="upload-preview" class="upload-preview"></div><div class="notice">OCR is intentionally not faked here. Uploaded screenshots will enter <b>Ready for OCR</b> until the provider is connected and the extracted values are verified.</div><div class="modal-actions"><button class="secondary" id="cancel-upload">Cancel</button><button class="primary" id="save-upload" disabled>Save screenshots</button></div></div>`;document.body.appendChild(m);const input=$('#shot-files'),preview=$('#upload-preview'),save=$('#save-upload');let selected=[];input.onchange=()=>{selected=[...input.files];preview.innerHTML=selected.map((x,i)=>`<div class="upload-file"><span>${i+1}</span><div><b>${esc(x.name)}</b><small>${Math.round(x.size/1024)} KB</small></div></div>`).join('');save.disabled=!selected.length};$('#cancel-upload').onclick=()=>m.remove();save.onclick=async()=>{save.disabled=true;save.textContent='Saving…';const existing=shots(f.id);for(const file of selected){const data=await readDataUrl(file);existing.push({id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type,data,status:'Ready for OCR',uploadedAt:new Date().toISOString()})}state.screenshots[String(f.id)]=existing;persist();m.remove();openGame(f.id)};}
function readDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function removeScreenshot(index){const id=String(state.selectedFixture);const arr=shots(state.selectedFixture);if(!arr[index])return;const name=arr[index].name;if(!confirm(`Remove ${name}? The source screenshot will be deleted from this browser. This cannot be undone.`))return;arr.splice(index,1);state.screenshots[id]=arr;persist();openGame(state.selectedFixture)}
function openModal(existingId){const existing=existingId?fixtureById(existingId):null;const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box"><div class="eyebrow">FIXTURE DATABASE</div><h2>${existing?'Edit fixture':'Add fixture'}</h2><div class="form-grid"><div class="field"><label>DATE</label><input id="f-date" type="date" value="${existing?existing.date:''}"></div><div class="field"><label>VENUE</label><input id="f-venue" value="${esc(existing?.venue||'')}" placeholder="Venue"></div><div class="field"><label>HOME TEAM</label><input id="f-home" value="${esc(existing?.home||"St Paul's")}"></div><div class="field"><label>AWAY TEAM</label><input id="f-away" value="${esc(existing?.away||'')}" placeholder="Opponent"></div></div><div class="modal-actions"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="save">${existing?'Save changes':'Save fixture'}</button></div></div>`;document.body.appendChild(m);$('#cancel').onclick=()=>m.remove();$('#save').onclick=()=>{const date=$('#f-date').value,home=$('#f-home').value.trim(),away=$('#f-away').value.trim();if(!date||!home||!away){$('#f-away').focus();return}if(existing)Object.assign(existing,{date,home,away,venue:$('#f-venue').value.trim()||'TBC'});else state.fixtures.push({id:Date.now(),date,home,away,venue:$('#f-venue').value.trim()||'TBC',status:'upcoming',scouted:false});persist();m.remove();render('fixtures')}}
$('#new-fixture').onclick=()=>openModal();document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>render(b.dataset.view));render();
