import {getAppData,saveAppData} from '../data/app-store.js';
import {validatePlayerRow,validateTeamTotals} from '../ocr/validation.js';
const FIELDS=['min','pts','fgm','fga','tpm','tpa','ftm','fta','oreb','dreb','reb','ast','stl','blk','to','pf','plusMinus'];
const value=v=>v===null||v===undefined||v===''?null:v;
const normKey=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases={fgm:['fgm','fgmade','fieldgoalsmade'],fga:['fga','fgattempts','fieldgoalsattempted'],tpm:['tpm','3pm','3ptm','3pointsmade'],tpa:['tpa','3pa','3pta','3pointsattempted'],ftm:['ftm','ftmade'],fta:['fta','ftattempts'],oreb:['oreb','offensiverebounds'],dreb:['dreb','defensiverebounds'],reb:['reb','rebounds'],pts:['pts','points'],ast:['ast','assists'],stl:['stl','steals'],blk:['blk','blocks'],to:['to','tov','turnovers'],pf:['pf','fouls'],min:['min','minutes'],plusMinus:['plusminus','plusminuspoints']};
function normalizeRow(row={}){const out={...row};for(const [target,names] of Object.entries(aliases)){if(value(out[target])!==null)continue;const k=Object.keys(row).find(key=>names.includes(normKey(key)));if(k)out[target]=row[k]}if(out.number==null)out.number=out.no??out.jersey??out['#'];if(!out.name)out.name=out.player??out.playerName??out['player name'];return out}
function mergeValue(target,field,incoming,source,conflicts){const v=value(incoming);if(v===null)return;const old=value(target[field]);if(old===null)target[field]=v;else if(String(old)!==String(v))conflicts.push({type:'value-conflict',player:target.name||target.number,field,existing:old,incoming:v,source});}
function mergeTotals(all){const out={home:{},away:{}};for(const totals of all){for(const side of ['home','away']){const t=normalizeRow(totals?.[side]||{});for(const field of FIELDS)if(value(t[field])!==null)out[side][field]=t[field]}}return out}
export async function scanGame(fixtureId){const d=getAppData();const fixture=d.fixtures.find(x=>String(x.id)===String(fixtureId));if(!fixture)throw Error('Game not found');const images=(d.screenshots||[]).filter(x=>String(x.fixtureId)===String(fixtureId));const pdf=(d.pdfs||[]).find(x=>String(x.fixtureId)===String(fixtureId));if(!images.length)throw Error('Add at least one screenshot first');fixture.status='scanning';saveAppData(d);const extractions=[];for(const image of images){try{const response=await request('/api/ocr',{image:image.data});extractions.push({...response.result,sourceFile:image.filename,provider:response.provider})}catch(error){extractions.push({rows:[],screenType:'unknown',confidence:0,notes:`${image.filename}: ${error.message}`,sourceFile:image.filename})}}let pdfResult={};if(pdf){try{pdfResult=(await request('/api/pdf',{pdf:pdf.data})).result||{}}catch(error){pdfResult={error:error.message}}}
const players=new Map(),evidence={},conflicts=[];for(const extraction of extractions){for(const raw of extraction.rows||[]){const row=normalizeRow(raw);if(!row.name&&row.number==null)continue;const key=row.number!=null?`#${String(row.number).trim()}:`:`name:${String(row.name).trim().toLowerCase()}`;const current=players.get(key)||{};for(const field of FIELDS)mergeValue(current,field,row[field],extraction.sourceFile,conflicts);current.number=current.number??row.number;current.name=current.name??row.name;players.set(key,current);evidence[key]=[...(evidence[key]||[]),extraction.sourceFile]}}
for(const raw of pdfResult.rows||[]){const row=normalizeRow(raw);if(!row.name&&row.number==null)continue;const key=row.number!=null?`#${String(row.number).trim()}:`:`name:${String(row.name).trim().toLowerCase()}`;const current=players.get(key)||{};for(const field of FIELDS)mergeValue(current,field,row[field],'official PDF',conflicts);current.number=current.number??row.number;current.name=current.name??row.name;players.set(key,current);evidence[key]=[...(evidence[key]||[]),'official PDF']}
const rows=[...players.values()].map(normalizeRow);const rowChecks=rows.map(row=>validatePlayerRow(row));const rowErrors=rowChecks.flatMap((check,index)=>check.errors.map(error=>`Player ${index+1}: ${error}`));const rowWarnings=rowChecks.flatMap((check,index)=>check.warnings.map(warning=>`Player ${index+1}: ${warning}`));const totals=mergeTotals([...extractions.map(x=>x.teamTotals||{}),pdfResult.teamTotals||{}]);const teamChecks={home:validateTeamTotals(totals.home),away:validateTeamTotals(totals.away)};const validationErrors=[...rowErrors,...teamChecks.home.errors.map(e=>`Home team: ${e}`),...teamChecks.away.errors.map(e=>`Away team: ${e}`)];const validationWarnings=[...rowWarnings,...teamChecks.home.warnings.map(e=>`Home team: ${e}`),...teamChecks.away.warnings.map(e=>`Away team: ${e}`)];const confidences=extractions.map(x=>Number(x.confidence)).filter(Number.isFinite).map(x=>x<=1?x*100:x);const avgConfidence=confidences.length?Math.round(confidences.reduce((a,b)=>a+b,0)/confidences.length):0;const quarters=pdfResult.quarterScores?.length?pdfResult.quarterScores:(extractions.find(x=>x.quarterScores?.length)?.quarterScores||[]);const rawVisibleStats=[...extractions.flatMap(x=>x.rawVisibleStats||[]),...(pdfResult.rawVisibleStats||[])];const stats={rows,teamTotals:totals,quarterScores:quarters,homeScore:pdfResult.homeScore??extractions.find(x=>x.homeScore!=null)?.homeScore??null,awayScore:pdfResult.awayScore??extractions.find(x=>x.awayScore!=null)?.awayScore??null,conflicts,validationErrors,validationWarnings,quality:{players:rows.length,screenshots:images.length,averageConfidence:avgConfidence,validRows:rowChecks.filter(x=>x.valid).length,invalidRows:rowChecks.filter(x=>!x.valid).length},ocrFiles:images.map(x=>x.filename),ocrNotes:extractions.map(x=>x.notes).filter(Boolean),pdfError:pdfResult.error||null,evidence,rawVisibleStats};
const reviewRequired=conflicts.length>0||validationErrors.length>0||avgConfidence<70||rows.length===0;const summary=validationErrors.length?`${validationErrors.length} validation issue${validationErrors.length===1?'':'s'} detected. Review the affected evidence before using this game for scouting.`:conflicts.length?`${conflicts.length} conflicting values detected across screenshots/PDF. Review the affected values before verification.`:rows.length?`Extraction complete: ${rows.length} players reconciled from ${images.length} screenshot${images.length===1?'':'s'}. Verify the game before relying on the report.`:'No player rows were extracted. The screenshots need another scan or a better OCR result.';d.reports=d.reports||[];d.reports=d.reports.filter(x=>String(x.fixtureId)!==String(fixtureId));d.reports.push({id:crypto.randomUUID(),fixtureId,createdAt:new Date().toISOString(),stats,verified:false,summary,sources:{screenshots:images.length,pdf:Boolean(pdf)}});fixture.status=reviewRequired?'review':'complete';saveAppData(d);return stats}
async function request(url,body){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw Error(payload.error||'Scan request failed');return payload}
