const NUMERIC_FIELDS=['min','pts','fgm','fga','tpm','tpa','ftm','fta','oreb','dreb','reb','ast','stl','blk','to','pf','plusMinus'];
const COUNT_FIELDS=NUMERIC_FIELDS.filter(k=>k!=='plusMinus');
const DERIVED_FIELDS=['fgPct','tpPct','ftPct','eff'];
const has=(row,k)=>row[k]!==undefined&&row[k]!==null&&row[k]!==''&&Number.isFinite(Number(row[k]));
const n=(row,k)=>Number(row[k]);
const normalizeRow=row=>{const out={...row};for(const key of [...NUMERIC_FIELDS,...DERIVED_FIELDS]){if(out[key]===undefined||out[key]===null||out[key]==='')continue;const value=Number(String(out[key]).replace(/[%+,]/g,''));if(Number.isFinite(value))out[key]=value}if(has(out,'fgm')&&has(out,'fga'))out.fgPct=out.fga?n(out,'fgm')/n(out,'fga')*100:0;if(has(out,'tpm')&&has(out,'tpa'))out.tpPct=out.tpa?n(out,'tpm')/n(out,'tpa')*100:0;if(has(out,'ftm')&&has(out,'fta'))out.ftPct=out.fta?n(out,'ftm')/n(out,'fta')*100:0;return out};
export function validatePlayerRow(row={}){const errors=[],warnings=[],r=normalizeRow(row);for(const key of NUMERIC_FIELDS){if(r[key]===null||r[key]===undefined||r[key]==='')continue;if(!has(r,key))errors.push(`${key} must be numeric`);else if(COUNT_FIELDS.includes(key)&&n(r,key)<0)errors.push(`${key} cannot be negative`)}if(has(r,'fgm')&&has(r,'fga')&&n(r,'fgm')>n(r,'fga'))errors.push('FGM cannot exceed FGA');if(has(r,'tpm')&&has(r,'tpa')&&n(r,'tpm')>n(r,'tpa'))errors.push('3PM cannot exceed 3PA');if(has(r,'ftm')&&has(r,'fta')&&n(r,'ftm')>n(r,'fta'))errors.push('FTM cannot exceed FTA');if(has(r,'tpm')&&has(r,'fgm')&&n(r,'tpm')>n(r,'fgm'))errors.push('3PM cannot exceed FGM');if(has(r,'oreb')&&has(r,'dreb')&&has(r,'reb')&&n(r,'oreb')+n(r,'dreb')!==n(r,'reb'))warnings.push('Rebounds do not equal offensive + defensive rebounds');if(has(r,'fgm')&&has(r,'tpm')&&has(r,'ftm')&&has(r,'pts')){const expected=2*(n(r,'fgm')-n(r,'tpm'))+3*n(r,'tpm')+n(r,'ftm');if(expected!==n(r,'pts'))errors.push(`Points do not reconcile with shooting stats (expected ${expected}, got ${n(r,'pts')})`)}return {valid:errors.length===0,errors,warnings,row:r}}
export function validateTeamTotals(team={}){const errors=[],warnings=[],t=normalizeRow(team);if(has(t,'fgm')&&has(t,'fga')&&n(t,'fgm')>n(t,'fga'))errors.push('FGM cannot exceed FGA');if(has(t,'tpm')&&has(t,'tpa')&&n(t,'tpm')>n(t,'tpa'))errors.push('3PM cannot exceed 3PA');if(has(t,'ftm')&&has(t,'fta')&&n(t,'ftm')>n(t,'fta'))errors.push('FTM cannot exceed FTA');if(t.reb!=null&&t.oreb!=null&&t.dreb!=null&&n(t,'oreb')+n(t,'dreb')!==n(t,'reb'))warnings.push('Team rebound components do not reconcile');return {valid:errors.length===0,errors,warnings,team:t}}
export function validateExtraction(result={}){const rows=result.rows||[],rowChecks=rows.map((r,i)=>({index:i,...validatePlayerRow(r)})),team=validateTeamTotals(result.teamTotals||{}),identity=new Set(),warnings=[...team.warnings],hardErrors=[...team.errors];rowChecks.forEach(x=>{hardErrors.push(...x.errors.map(e=>`Player ${x.index+1}: ${e}`));warnings.push(...x.warnings.map(e=>`Player ${x.index+1}: ${e}`));const key=String(x.row.number??x.row.name??'').trim().toLowerCase();if(key&&identity.has(key))warnings.push(`Duplicate player identity: ${x.row.number??x.row.name}`);if(key)identity.add(key)});if(result.screenType==='box-score'&&!rows.length)hardErrors.push('Box-score extraction contains no player rows');const modelConfidence=Number(result.confidence);if(Number.isFinite(modelConfidence)){const c=modelConfidence<=1?modelConfidence*100:modelConfidence;if(c<70)warnings.push(`Model confidence is low (${Math.round(c)}%)`)}const checks=rows.reduce((sum,r)=>sum+NUMERIC_FIELDS.filter(k=>has(r,k)).length,0);const passed=rowChecks.reduce((sum,x)=>sum+NUMERIC_FIELDS.filter(k=>has(x.row,k)&&!x.errors.some(e=>e.startsWith(k))).length,0);const quality=Math.max(0,Math.min(100,Math.round((rows.length?65:20)+(checks?35*Math.min(1,passed/checks):0)-hardErrors.length*12-warnings.length*3)));return {valid:hardErrors.length===0,team,rowChecks,hardErrors,warnings,quality,status:hardErrors.length?'reject':quality>=90?'high-confidence':quality>=75?'review':'low-confidence'}}
export function normalizeVerifiedRows(rows=[]){return rows.map(normalizeRow)}
