import './styles.css';
import {getAppData,createFixture,saveFixture,clearAppData} from './data/app-store.js';
import {mountFixtureWorkspace} from './ui/fixture-controller.js';

const app=document.querySelector('#app');let activeFixture=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function shell(content){app.innerHTML=`<div class="app"><aside><div class="brand"><span class="brand-mark">C</span><div><strong>CourtIQ</strong><small>Basketball intelligence</small></div></div><nav><button data-nav="dashboard" class="nav active">Overview</button><button data-nav="fixtures" class="nav">Fixtures</button></nav><div class="side-note"><b>Evidence first</b><p>Every screenshot stays attached to its fixture. Unverified OCR never becomes scouting truth.</p></div></aside><main>${content}</main></div>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='fixtures'?renderFixtures():renderDashboard())}
function renderDashboard(){const d=getAppData();shell(`<header class="top"><div><span class="eyebrow">COURTIQ</span><h1>Scouting overview</h1><p>Your verified basketball intelligence workspace.</p></div><button class="primary" id="new-fixture">+ New fixture</button></header><section class="stats"><div><span>Fixtures</span><strong>${d.fixtures.length}</strong></div><div><span>Source screenshots</span><strong>${d.screenshots.length}</strong></div><div><span>OCR extractions</span><strong>${d.extractions.length}</strong></div><div><span>Verified values</span><strong>${d.verifications.length}</strong></div></section><section class="panel"><div class="panel-head"><div><h2>Recent fixtures</h2><p>Games are independent workspaces.</p></div><button class="ghost" id="view-fixtures">View all</button></div>${fixtureCards(d.fixtures.slice().reverse().slice(0,6))}</section>`);document.querySelector('#new-fixture').onclick=showFixtureForm;document.querySelector('#view-fixtures').onclick=renderFixtures}
function fixtureCards(fixtures){return fixtures.length?`<div class="fixture-list">${fixtures.map(f=>`<button class="fixture-card" data-fixture="${f.id}"><div><span class="date">${esc(f.date||'Date not set')}</span><h3>${esc(f.home||'Home')} <em>vs</em> ${esc(f.away||'Away')}</h3><p>${esc(f.competition)} · ${esc(f.venue||'Venue not set')}</p></div><span class="arrow">→</span></button>`).join('')}</div>`:'<div class="empty-card"><h3>No fixtures yet</h3><p>Create a fixture before uploading Swish screenshots.</p></div>'}
function bindCards(){document.querySelectorAll('[data-fixture]').forEach(b=>b.onclick=()=>openFixture(b.dataset.fixture))}
function renderFixtures(){const d=getAppData();shell(`<header class="top"><div><span class="eyebrow">GAME LIBRARY</span><h1>Fixtures</h1><p>Keep every game separate, week by week.</p></div><button class="primary" id="new-fixture">+ New fixture</button></header><section class="panel">${fixtureCards(d.fixtures.slice().reverse())}</section>`);document.querySelector('#new-fixture').onclick=showFixtureForm;bindCards()}
function showFixtureForm(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<form class="modal"><button type="button" class="close">×</button><span class="eyebrow">NEW FIXTURE</span><h2>Create game workspace</h2><p>Define the game first. Screenshots are then attached to this fixture.</p><div class="form-grid"><label>Home team<input name="home" required placeholder="St Paul's"></label><label>Away team<input name="away" required placeholder="Malahide"></label><label>Date<input name="date" type="date"></label><label>Venue<input name="venue" placeholder="Venue"></label><label>Competition<input name="competition" value="Irish National League"></label><label>Season<input name="season" value="2026-27"></label></div><button class="primary full">Create fixture</button></form>`;document.body.append(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('form').onsubmit=e=>{e.preventDefault();const f=createFixture(Object.fromEntries(new FormData(e.target)));modal.remove();openFixture(f.id)}}
function openFixture(id){activeFixture=getAppData().fixtures.find(f=>String(f.id)===String(id));if(!activeFixture)return;renderWorkspace()}
function renderWorkspace(){shell(`<div id="workspace-root"></div>`);const root=document.querySelector('#workspace-root');const controller=mountFixtureWorkspace(root,activeFixture);const back=document.createElement('button');back.className='back';back.textContent='← Back to fixtures';back.onclick=renderFixtures;root.prepend(back);window.__fixtureRefresh=controller.refresh}
renderDashboard();
window.addEventListener('storage',()=>activeFixture?renderWorkspace():renderDashboard());
