import './styles.css';
import './report-visuals.css';
import {getAppData,createFixture} from './data/app-store.js';
import {mountFixtureWorkspace} from './ui/fixture-controller.js';
const app=document.querySelector('#app');let activeFixture=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function shell(content){app.innerHTML=`<div class="app"><aside><div class="brand"><span class="brand-mark">C</span><div><strong>CourtIQ</strong><small>Basketball intelligence</small></div></div><nav><button data-nav="dashboard" class="nav active">Overview</button><button data-nav="fixtures" class="nav">Fixtures</button></nav><div class="side-note"><b>Simple by design</b><p>Upload the whole game. Click one button. CourtIQ builds the report.</p></div></aside><main>${content}</main></div>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='fixtures'?renderFixtures():renderDashboard())}
function renderDashboard(){const d=getAppData();shell(`<header class="top"><div><span class="eyebrow">COURTIQ</span><h1>Game reports</h1><p>Upload a game's Swish screenshots and scan them into a scouting report.</p></div><button class="primary" id="new-fixture">+ New game</button></header><section class="stats"><div><span>Games</span><strong>${d.fixtures.length}</strong></div><div><span>Reports</span><strong>${(d.reports||[]).length}</strong></div><div><span>Sources</span><strong>${d.screenshots.length+(d.pdfs||[]).length}</strong></div></section><section class="panel"><div class="panel-head"><div><h2>Recent games</h2><p>Each game has its own independent workspace.</p></div><button class="ghost" id="view-fixtures">View all</button></div>${fixtureCards(d.fixtures.slice().reverse().slice(0,6))}</section>`);document.querySelector('#new-fixture').onclick=showFixtureForm;document.querySelector('#view-fixtures').onclick=renderFixtures;bindCards()}
function fixtureCards(fs){return fs.length?`<div class="fixture-list">${fs.map(f=>`<button class="fixture-card" data-fixture="${f.id}"><div><span class="date">${esc(f.date||'Date not set')}</span><h3>${esc(f.home||'Home')} <em>vs</em> ${esc(f.away||'Away')}</h3><p>${esc(f.competition||'Game')} · ${esc(f.status||'collecting')}</p></div><span class="arrow">→</span></button>`).join('')}</div>`:'<div class="empty-card"><h3>No games yet</h3><p>Create your first game to upload Swish screenshots.</p></div>'}
function bindCards(){document.querySelectorAll('[data-fixture]').forEach(b=>b.onclick=()=>openFixture(b.dataset.fixture))}
function renderFixtures(){const d=getAppData();shell(`<header class="top"><div><span class="eyebrow">GAME LIBRARY</span><h1>Games</h1><p>Every week's game stays independent.</p></div><button class="primary" id="new-fixture">+ New game</button></header><section class="panel">${fixtureCards(d.fixtures.slice().reverse())}</section>`);document.querySelector('#new-fixture').onclick=showFixtureForm;bindCards()}
function showFixtureForm(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<form class="modal"><button type="button" class="close">×</button><span class="eyebrow">NEW GAME</span><h2>Create game</h2><div class="form-grid"><label>Home team<input name="home" required placeholder="St Paul's"></label><label>Away team<input name="away" required placeholder="Malahide"></label><label>Date<input name="date" type="date"></label><label>Venue<input name="venue" placeholder="Venue"></label><label>Competition<input name="competition" value="Irish National League"></label><label>Season<input name="season" value="2026-27"></label></div><button class="primary full">Create game</button></form>`;document.body.append(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('form').onsubmit=e=>{e.preventDefault();const f=createFixture(Object.fromEntries(new FormData(e.target)));modal.remove();openFixture(f.id)}}
function openFixture(id){activeFixture=getAppData().fixtures.find(f=>String(f.id)===String(id));if(activeFixture)renderWorkspace()}
function renderWorkspace(){shell('<div id="workspace-root"></div>');const root=document.querySelector('#workspace-root');const c=mountFixtureWorkspace(root,activeFixture);window.__fixtureRefresh=c.refresh}
renderDashboard();window.addEventListener('storage',()=>activeFixture?renderWorkspace():renderDashboard());
